---
title: "Forecasting daily electricity load using `fable` and `modeltime`"
subtitle: "IDI-II. PhD in Engineering Sciences"
date: 2020-08-20
author: "Pablo Benavides-Herrera"
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
    theme: journal
    highligh: tango
    number_sections: TRUE
---


# Introduction

This notebook contains 

## Packages

The packages necessary to run this notebook are the following.

```{r pkgs, message=FALSE, warning=FALSE}
library(tidyverse) # data cleaning, wrangling, plotting
library(lubridate) # dates handling
library(patchwork) # plot setup
library(plotly)    # interactive plots

# the tidyverts
library(tsibble)
library(feasts)
library(fable)

# modeltime
library(tidymodels)
library(modeltime)
```


# `R` Packages for modeling and forecasting

We will produce forecasts using a wide variety of models, with two different `R` packages: `fable` and `modeltime`.

## `fable` and the tidyver**ts** ecosystem

## `modeltime`: and extension to the `tidymodels`

# The models

Below we implement many of the models available in both packages.

## Exponential smoothing {.tabset .tabset-fade}

### .

### `fable`

### `modeltime`

### {-}

## ARIMA {.tabset .tabset-fade}

### .

### `fable`

### `modeltime`

### {-}

## Linear regression {.tabset}

### .

### `fable`

### `modeltime`

### {-}

## Dynamic regression {.tabset}

### .

### `fable`

### `modeltime`

### {-}

## Prophet {.tabset}

### .

### `fable`

### `modeltime`

### {-}

## FASSTER {.tabset}

### .

### `fable`


### `modeltime`

### {-}

## The proposed model


# Comparison across models

## Training adjustment

## Forecasting adjustment

## Cross-validation

## Forecasts


# Conclusions
